-- liquibase formatted sql

--changeset Robin.Mayer:1718962987-1
CREATE TABLE public.users (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    email varchar(255) NULL,
    last_login timestamp(6) NULL,
    "name" varchar(255) NULL,
    "password" varchar(255) NULL,
    user_id varchar(255) NULL,
    verified bool NOT NULL,
    verification_code varchar(255) NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);